"use client";

import Link from "next/link";
import type { ThesisMilestoneView } from "@/lib/thesis-progress/thesis-domain";
import { getThesisProgressSummary } from "@/lib/thesis-progress/thesis-domain";
import { ThesisMilestoneCard } from "@/components/thesis-progress/ThesisMilestoneCard";

export function ThesisProgressTracker({ milestones }: { milestones: ThesisMilestoneView[] }) {
  const summary = getThesisProgressSummary(milestones);
  const currentLabel = summary.current?.status === "blocked" ? `目前卡在：${summary.current.label}` : summary.allCompleted ? "所有論文里程碑已完成" : summary.current?.label ?? "尚未設定";
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top,rgba(37,99,235,0.18),transparent_34rem),linear-gradient(180deg,#020617_0%,#0f172a_100%)] px-4 py-10 text-white"><div className="mx-auto w-full max-w-5xl space-y-7"><Link href="/dashboard" className="text-sm font-semibold text-cyan-200 hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300/70">← 回研究工作台</Link><header className="rounded-[2rem] border border-white/10 bg-slate-950/80 p-7"><p className="text-xs font-semibold uppercase tracking-[0.28em] text-cyan-200">THESIS PROGRESS</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">論文進度</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">用幾個關鍵里程碑看清楚自己目前的位置，知道已經完成什麼，以及下一步要往哪裡走。</p><p className="mt-5 rounded-2xl border border-amber-300/15 bg-amber-300/[0.06] px-4 py-3 text-sm leading-6 text-amber-50">這裡顯示的是論文里程碑完成度，不是畢業機率，也不是學校正式畢業審核結果。</p></header><section className="grid gap-3 md:grid-cols-3"><div className="rounded-3xl border border-cyan-300/15 bg-cyan-400/[0.06] p-5"><p className="text-xs uppercase tracking-[0.18em] text-cyan-200">目前階段</p><p className="mt-3 font-semibold leading-6">{currentLabel}</p></div><div className="rounded-3xl border border-blue-300/15 bg-blue-400/[0.06] p-5"><p className="text-xs uppercase tracking-[0.18em] text-blue-200">里程碑完成度</p><p className="mt-3 text-2xl font-semibold">{summary.completedCount} / {summary.totalCount}</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-blue-400" style={{ width: `${(summary.completedCount / summary.totalCount) * 100}%` }} /></div></div><div className="rounded-3xl border border-emerald-300/15 bg-emerald-400/[0.06] p-5"><p className="text-xs uppercase tracking-[0.18em] text-emerald-200">下一個目標</p><p className="mt-3 font-semibold">{summary.current?.target_date ?? "尚未設定"}</p></div></section><p className="text-sm leading-6 text-slate-400">不用一次填完。先找到最接近你目前研究狀況的階段，設定狀態與目標日期即可。</p><section className="space-y-4" aria-label="論文里程碑時間軸">{milestones.map((milestone) => <ThesisMilestoneCard key={milestone.key} milestone={milestone} focusId={milestone.status === "blocked" ? "blocked-milestone" : undefined} />)}</section></div></main>;
}
