"use client";

import Link from "next/link";
import { FormEvent } from "react";
import { formatTaipeiMeetingDateTime } from "@/lib/meetings/meeting-time";

export type StudentRiskLevel = "low" | "medium" | "high";
export type StudentLeadSummary = { quiz_result: StudentRiskLevel | null; quiz_score: number | null; main_tags: string[] | null };

export type StudentWorkspaceHomeProps = {
  leadSummary: StudentLeadSummary | null;
  isLoading?: boolean;
  advisorStyle?: string;
  frequentQuestions?: string;
  onAdvisorStyleChange?: (value: string) => void;
  onFrequentQuestionsChange?: (value: string) => void;
  onSubmitAdvisorMemory?: (event: FormEvent<HTMLFormElement>) => void;
  isSaving?: boolean;
  message?: string;
  previewMode?: boolean;
  accessSummary?: { course: string; audit: string; lab: string };
  weeklyCheckIn?: { updatedAt: string | null };
  meetingSummary?: { pendingCount: number; nextMeetingAt: string | null };
  actionSummary?: { overdueCount: number; dueSoonCount: number; openCount: number };
  thesisSummary?: { currentLabel: string; completedCount: number; blocked: boolean };
  graduationRisk?: { status: "urgent" | "attention" | "stable" | "setup_needed"; label: string; reason: string };
  advisorConfigured?: boolean;
  learningSummary?: { courseTitle: string; lessonTitle: string | null; completedCount: number; visibleCount: number };
};

const quizLabels: Record<StudentRiskLevel, string> = { low: "低", medium: "中", high: "高" };
const tagLabels: Record<string, string> = { tag_literature_blocked: "文獻閱讀卡關", tag_advisor_meeting_blocked: "Meeting 壓力", tag_presentation_blocked: "簡報失焦", tag_tooling_blocked: "工具落差", tag_high_stress: "高焦慮" };
const cardClass = "rounded-3xl border border-white/10 bg-white/[0.04] p-6";
const weeklyUpdatedCta = "查看 / 更新本週進度";

function ActionSummary({ actionSummary }: { actionSummary?: StudentWorkspaceHomeProps["actionSummary"] }) {
  const summary = actionSummary ?? { overdueCount: 0, dueSoonCount: 0, openCount: 0 };
  const text = summary.overdueCount ? `${summary.overdueCount} 項已逾期` : summary.dueSoonCount ? `未來 14 天 ${summary.dueSoonCount} 項` : summary.openCount ? `${summary.openCount} 項待處理` : "目前沒有待處理 Action";
  return <Link href="/dashboard/actions" className={`${cardClass} border-cyan-300/20 bg-cyan-400/[0.07] transition hover:border-cyan-300/40`}><p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-200">我的下一步</p><p className="mt-3 text-lg font-semibold">{text}</p><p className="mt-2 text-sm text-slate-400">把 Meeting 決定轉成可以完成的研究行動。</p><span className="mt-5 inline-flex rounded-xl bg-cyan-400 px-3 py-2 text-xs font-semibold text-slate-950">查看下一步</span></Link>;
}

export function StudentWorkspaceHome({ leadSummary, isLoading = false, previewMode = false, accessSummary, weeklyCheckIn, meetingSummary, actionSummary, thesisSummary, graduationRisk, advisorConfigured = false, learningSummary }: StudentWorkspaceHomeProps) {
  const risk = graduationRisk ?? { status: "setup_needed" as const, label: "先建立你的研究導航", reason: "先設定論文進度或加入 Lab" };
  const riskStyles = { urgent: "border-red-300/30 bg-red-400/[0.08]", attention: "border-amber-300/30 bg-amber-400/[0.08]", stable: "border-emerald-300/25 bg-emerald-400/[0.06]", setup_needed: "border-cyan-300/25 bg-cyan-400/[0.06]" };
  const primaryHref = risk.status === "urgent" || risk.status === "attention" ? "/dashboard/graduation-risk" : risk.status === "setup_needed" ? "/dashboard/thesis" : "/dashboard/thesis";
  const nextMeeting = meetingSummary?.nextMeetingAt ? formatTaipeiMeetingDateTime(meetingSummary.nextMeetingAt) : "尚未安排 Meeting";
  const quiz = leadSummary?.quiz_result;
  void weeklyUpdatedCta;

  return <main className="min-h-screen overflow-x-hidden bg-[radial-gradient(circle_at_top,rgba(37,99,235,0.20),transparent_34rem),linear-gradient(180deg,#020617_0%,#0f172a_100%)] px-4 py-8 text-white sm:py-12"><section className="mx-auto w-full max-w-6xl space-y-8">
    {previewMode ? <div className="rounded-2xl border border-amber-300/30 bg-amber-300/10 px-5 py-3 text-sm leading-6 text-amber-50">Admin Preview Mode：此為固定情境資料，儲存、付款、上傳與其他操作均不會執行。</div> : null}
    <header className={`${cardClass} border-cyan-300/20 bg-slate-950/85 p-7 shadow-2xl shadow-blue-950/30 sm:p-9`}><p className="text-xs font-semibold uppercase tracking-[0.28em] text-cyan-200">CURRENT RESEARCH STATUS</p><div className="mt-4 flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">我的研究狀態</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">掌握研究進度、下一步與目前需要注意的事情。</p><p className="mt-6 text-2xl font-semibold">{risk.label}</p><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">{risk.reason}</p></div>{previewMode ? <button type="button" disabled className="rounded-xl bg-cyan-400/50 px-5 py-3 text-sm font-semibold text-slate-950">處理現在最重要的事</button> : <Link href={primaryHref} className="inline-flex shrink-0 rounded-xl bg-cyan-400 px-5 py-3 text-sm font-semibold text-slate-950 transition hover:bg-cyan-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-200/80">{risk.status === "setup_needed" ? "設定論文進度" : "處理現在最重要的事"}</Link>}</div></header>
    <section aria-labelledby="now-heading"><div className="flex items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-cyan-200">NOW</p><h2 id="now-heading" className="mt-2 text-2xl font-semibold">現在</h2></div></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><ActionSummary actionSummary={actionSummary}/><Link href="/dashboard/meetings" className={`${cardClass} transition hover:border-blue-300/30`}><p className="text-xs font-semibold uppercase tracking-[0.2em] text-blue-200">下一場 Meeting</p><p className="mt-3 text-lg font-semibold">{nextMeeting}</p><p className="mt-2 text-sm text-slate-400">{meetingSummary?.pendingCount ? `${meetingSummary.pendingCount} 場 Meeting 待補紀錄` : "準備下一次討論，讓研究繼續往前。"}</p><span className="mt-5 inline-flex rounded-xl bg-blue-400/15 px-3 py-2 text-xs font-semibold text-blue-100">查看 Meeting</span></Link></div></section>
    <section aria-labelledby="week-heading"><p className="text-xs font-semibold uppercase tracking-[0.24em] text-cyan-200">THIS WEEK</p><h2 id="week-heading" className="mt-2 text-2xl font-semibold">本週</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><Link href="/dashboard/weekly-check-in" className={cardClass}><p className="text-sm text-slate-400">Weekly</p><p className="mt-3 font-semibold">{weeklyCheckIn?.updatedAt ? "✓ 已更新" : "本週尚未更新"}</p><span className="mt-4 inline-flex text-xs font-semibold text-cyan-200">{weeklyCheckIn?.updatedAt ? "查看 / 更新" : "填寫本週進度"}</span></Link><Link href="/dashboard/meetings" className={cardClass}><p className="text-sm text-slate-400">Meeting</p><p className="mt-3 font-semibold">{nextMeeting}</p><span className="mt-4 inline-flex text-xs font-semibold text-blue-200">查看 Meeting</span></Link><Link href="/dashboard/actions" className={cardClass}><p className="text-sm text-slate-400">Actions</p><p className="mt-3 font-semibold">{actionSummary?.openCount ?? 0} open · {actionSummary?.overdueCount ?? 0} overdue</p><span className="mt-4 inline-flex text-xs font-semibold text-cyan-200">查看下一步</span></Link></div></section>
    <section aria-labelledby="thesis-heading"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-blue-200">THESIS JOURNEY</p><h2 id="thesis-heading" className="mt-2 text-2xl font-semibold">論文進度</h2></div><Link href="/dashboard/thesis" className="text-sm font-semibold text-cyan-200 hover:text-white">查看完整進度</Link></div><div className={`${cardClass} mt-4 border-blue-300/20`}><p className="text-sm text-slate-400">目前階段</p><p className="mt-3 text-xl font-semibold">{thesisSummary?.currentLabel ?? "尚未設定"}</p><p className="mt-2 text-sm text-slate-400">{thesisSummary ? `完成 ${thesisSummary.completedCount} / 8${thesisSummary.blocked ? ` · 目前卡在：${thesisSummary.currentLabel}` : ""}` : "先設定論文進度，建立你的研究導航。"}</p></div></section>
    <section className={`${cardClass} ${riskStyles[risk.status]}`}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-400">GRADUATION NAVIGATION</p><h2 className="mt-2 text-xl font-semibold">畢業風險</h2><p className="mt-2 text-sm text-slate-300">{risk.label} · {risk.reason}</p></div><Link href="/dashboard/graduation-risk" className="rounded-xl border border-white/15 px-3 py-2 text-xs font-semibold text-slate-100 hover:bg-white/[0.08]">查看風險</Link></div></section>
    <section aria-labelledby="context-heading"><p className="text-xs font-semibold uppercase tracking-[0.24em] text-slate-400">RECENT RESEARCH CONTEXT</p><h2 id="context-heading" className="mt-2 text-2xl font-semibold">最近研究紀錄</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className={cardClass}><p className="text-sm text-slate-400">初始研究狀態診斷</p>{isLoading ? <p className="mt-3 text-sm text-slate-500">讀取中...</p> : quiz ? <><p className="mt-3 font-semibold">診斷結果：{quizLabels[quiz]}度</p><div className="mt-3 flex flex-wrap gap-2">{(leadSummary?.main_tags ?? []).map((tag) => <span key={tag} className="rounded-full border border-white/10 px-3 py-1 text-xs text-slate-300">{tagLabels[tag] ?? tag}</span>)}</div></> : <p className="mt-3 text-sm leading-6 text-slate-400">尚未完成初始診斷。這是入站時的研究狀態紀錄，不是目前畢業風險。</p>}<Link href="/quiz" className="mt-4 inline-flex text-xs font-semibold text-cyan-200 hover:text-white">查看初始診斷</Link></div><div className={cardClass}><p className="text-sm text-slate-400">研究節奏</p><p className="mt-3 font-semibold">{weeklyCheckIn?.updatedAt ? "最近已更新 Weekly" : "本週尚未留下進度"}</p><p className="mt-2 text-sm text-slate-400">用下一次 Weekly 接續目前的研究狀況。</p></div></div></section>
    <section aria-labelledby="learning-heading" className={`${cardClass} border-cyan-300/20 bg-cyan-400/[0.05]`}><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-cyan-200">LEARNING CENTER</p><h2 id="learning-heading" className="mt-2 text-xl font-semibold">課程學習</h2><p className="mt-2 text-sm text-slate-400">{learningSummary?.courseTitle || "開始 RAPID 核心課程"}</p><p className="mt-1 text-sm font-semibold text-slate-200">{learningSummary?.lessonTitle ? `繼續：${learningSummary.lessonTitle}` : learningSummary?.visibleCount ? `${learningSummary.completedCount} / ${learningSummary.visibleCount} 已完成` : "前往課程學習"}</p></div><Link href="/learn" className="inline-flex shrink-0 rounded-xl bg-cyan-400 px-4 py-3 text-center text-xs font-semibold text-slate-950">{learningSummary?.lessonTitle ? "繼續觀看" : "前往課程"}</Link></div></section>
    <section aria-labelledby="tools-heading"><p className="text-xs font-semibold uppercase tracking-[0.24em] text-slate-400">RESEARCH TOOLS</p><h2 id="tools-heading" className="mt-2 text-2xl font-semibold">研究工具</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><Link href="/dashboard/ai-command" className={cardClass}><p className="font-semibold">AI 指令產生器</p><p className="mt-2 text-sm text-slate-400">準備 Meeting 前的研究檢查指令。</p></Link><Link href="/dashboard/ai-audit" className={cardClass}><p className="font-semibold">PDF AI 稽核</p><p className="mt-2 text-sm text-slate-400">檢查研究文件與圖表。</p></Link><Link href="/dashboard/ai-audit/history" className={cardClass}><p className="font-semibold">稽核歷史</p><p className="mt-2 text-sm text-slate-400">查看過去的稽核結果。</p></Link></div></section>
    <section aria-labelledby="utility-heading"><p className="text-xs font-semibold uppercase tracking-[0.24em] text-slate-500">SETUP & UTILITY</p><h2 id="utility-heading" className="mt-2 text-2xl font-semibold">工作區設定</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{accessSummary ? <div className={cardClass}><p className="text-sm text-slate-400">工作區存取</p><p className="mt-3 text-sm leading-6 text-slate-300">Lab：{accessSummary.lab}<br/>課程：{accessSummary.course}<br/>PDF：{accessSummary.audit}</p></div> : null}<Link href="/dashboard/lab-join" className={cardClass}><p className="font-semibold">加入 Lab</p><p className="mt-2 text-sm text-slate-400">連結你的研究指導工作區。</p></Link><Link href="/dashboard/course" className={cardClass}><p className="font-semibold">課程觀看</p><p className="mt-2 text-sm text-slate-400">查看研究學習資源。</p></Link><Link href="/dashboard/advisor-profile" className={cardClass}><p className="font-semibold">教授偏好</p><p className="mt-2 text-sm text-slate-400">{advisorConfigured ? "已設定 ✓" : "尚未設定教授偏好"}</p><span className="mt-4 inline-flex text-xs font-semibold text-cyan-200">管理教授偏好</span></Link></div></section>
  </section></main>;
}
