"use client";

import { useActionState } from "react";
import { createMeetingAction, type MeetingActionState } from "@/app/dashboard/actions/actions";

const initialState: MeetingActionState = { status: "idle", message: "" };

export function ActionCreateForm({ meetingId, supervisor = false, disabled = false }: { meetingId: string; supervisor?: boolean; disabled?: boolean }) {
  const [state, formAction, isPending] = useActionState(createMeetingAction, initialState);
  return <form action={formAction} className="mt-4 space-y-3 rounded-2xl border border-cyan-300/15 bg-cyan-400/[0.04] p-4"><input type="hidden" name="meeting_id" value={meetingId} /><label className="block text-sm text-slate-200"><span>下一步</span><textarea name="title" required maxLength={500} disabled={disabled || isPending} className="mt-2 min-h-20 w-full rounded-xl border border-white/10 bg-slate-950/70 px-3 py-2.5 text-sm text-white outline-none focus-visible:ring-2 focus-visible:ring-cyan-300/70 disabled:opacity-50" placeholder="例如：補跑 3000 K 模擬並整理 RDF 圖" /><span className="mt-1 block text-xs text-slate-500">寫成下一步可以實際完成的動作，而不是研究主題。</span></label>{supervisor ? <label className="block text-sm text-slate-200"><span>負責人</span><select name="owner_choice" defaultValue="student" disabled={disabled || isPending} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus-visible:ring-2 focus-visible:ring-cyan-300/70"><option value="student">學生</option><option value="self">我</option></select></label> : <p className="text-sm text-slate-400">負責人：你</p>}<label className="block text-sm text-slate-200"><span>截止日期（選填）</span><input name="due_date" type="date" disabled={disabled || isPending} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus-visible:ring-2 focus-visible:ring-cyan-300/70 disabled:opacity-50" /></label><button type="submit" disabled={disabled || isPending} className="rounded-xl bg-blue-500 px-4 py-2 text-sm font-semibold text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300/70 disabled:cursor-not-allowed disabled:opacity-50">{isPending ? "建立中..." : supervisor ? "建立 Meeting Action" : "新增下一步"}</button>{state.message ? <p role={state.status === "error" ? "alert" : "status"} className={`text-sm ${state.status === "error" ? "text-red-200" : "text-emerald-200"}`}>{state.message}</p> : null}</form>;
}
