import Link from "next/link";
import { answerCourseQuestion, resolveCourseQuestion } from "@/app/admin/course/actions";
import { aggregateLessonIntelligence, formatWatchTime, type IntelligenceQuestion, type IntelligenceSegment, type IntelligenceSession, type IntelligenceVersion } from "@/lib/course/intelligence";

type Lesson = { id: string; title: string; module_key: string; is_published: boolean; publication_state: string; video_status: string };

function StateBadge({ state }: { state: string }) {
  const label = state === "live" ? "已上架" : state === "paused" ? "暫停上架" : state === "archived" ? "已封存" : "草稿";
  const style = state === "live" ? "border-emerald-300/25 bg-emerald-300/10 text-emerald-100" : state === "paused" ? "border-amber-300/25 bg-amber-300/10 text-amber-100" : "border-white/15 text-slate-300";
  return <span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${style}`}>{label}</span>;
}

function QuestionActions({ question }: { question: IntelligenceQuestion }) {
  if (!question.id || question.status === "resolved") return null;
  return <div className="mt-4 flex flex-wrap gap-3 border-t border-white/10 pt-4">
    {question.kind === "question" && question.status === "open" ? <form action={answerCourseQuestion} className="flex min-w-[min(100%,32rem)] flex-1 gap-2"><input type="hidden" name="questionId" value={question.id} /><label className="sr-only" htmlFor={`answer-${question.id}`}>回答學生</label><input id={`answer-${question.id}`} name="answer" required placeholder="輸入給學生的回答" className="min-w-0 flex-1 rounded-lg border border-white/10 bg-slate-950 px-3 py-2 text-sm text-white" /><button type="submit" className="rounded-lg bg-cyan-400 px-3 py-2 text-xs font-semibold text-slate-950">回答</button></form> : null}
    {question.status === "answered" && question.admin_answer ? <p className="w-full rounded-lg border border-cyan-300/15 bg-cyan-300/[0.06] px-3 py-2 text-sm text-cyan-50">管理者回答：{question.admin_answer}</p> : null}
    <form action={resolveCourseQuestion}><input type="hidden" name="questionId" value={question.id} /><button type="submit" className="rounded-lg border border-emerald-300/25 px-3 py-2 text-xs font-semibold text-emerald-100">標記已解決</button></form>
  </div>;
}

export default function CourseIntelligencePanels({ view, lessons, sessions, segments, questions, versions }: { view: "attention" | "analytics" | "questions" | "students" | "versions"; lessons: Lesson[]; sessions: IntelligenceSession[]; segments: IntelligenceSegment[]; questions: IntelligenceQuestion[]; versions: IntelligenceVersion[] }) {
  const metrics = lessons.map((lesson) => ({ lesson, metric: aggregateLessonIntelligence(lesson.id, sessions, segments, questions) }));
  if (view === "students") return <section className="mt-5 rounded-2xl border border-white/10 bg-white/[0.035] p-5"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-200">Learners</p><h2 className="mt-2 text-xl font-semibold">學生學習狀態</h2><p className="mt-2 text-sm text-slate-400">僅供具權限的管理員檢視；學生以匿名識別碼顯示，不在頁面暴露 Email。</p><div className="mt-5 grid gap-3 lg:grid-cols-2">{sessions.length ? Array.from(new Map(sessions.map((session) => [`${session.lesson_id}:${session.user_id}`, session])).values()).map((session) => { const lesson = lessons.find((item) => item.id === session.lesson_id); const status = session.completed_at ? "已完成" : session.watch_time_seconds > 0 ? "觀看中" : "尚未開始"; return <article key={`${session.lesson_id}:${session.user_id}`} className="rounded-xl border border-white/10 bg-slate-950/50 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-white">{lesson?.title ?? "課程單元"}</p><p className="mt-1 text-xs text-slate-500">學生 {session.user_id.slice(0, 8)}…</p></div><span className="rounded-full border border-cyan-300/20 px-2.5 py-1 text-xs text-cyan-100">{status}</span></div><div className="mt-4 grid grid-cols-3 gap-3 text-sm"><p><span className="block text-xs text-slate-500">觀看</span>{formatWatchTime(session.watch_time_seconds)}</p><p><span className="block text-xs text-slate-500">目前位置</span>{formatWatchTime(session.last_position_seconds)}</p><p><span className="block text-xs text-slate-500">最後活動</span>{session.created_at ? new Date(session.created_at).toLocaleDateString("zh-TW") : "-"}</p></div></article>; }) : <p className="rounded-xl border border-white/10 p-5 text-sm text-slate-400">目前沒有學生觀看資料。</p>}</div></section>;
  if (view === "versions") return <section className="mt-5 rounded-2xl border border-white/10 bg-white/[0.035] p-5"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-200">Video Versions</p><h2 className="mt-2 text-xl font-semibold">影片版本</h2><p className="mt-2 text-sm text-slate-400">每次上傳建立新版本；舊版本保留供稽核，不會被管理介面誤刪。</p><div className="mt-5 space-y-3">{versions.length ? versions.map((version) => { const lesson = lessons.find((item) => item.id === version.lesson_id); return <article key={version.id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-white/10 bg-slate-950/50 p-4"><div><p className="font-semibold text-white">{lesson?.title ?? "課程單元"} · v{version.version_number}</p><p className="mt-1 text-xs text-slate-500">{version.video_provider.toUpperCase()} · {version.playback_id ? "已有 Playback ID" : "等待處理"}</p></div><div className="flex items-center gap-3"><span className={`rounded-full border px-2.5 py-1 text-xs ${version.status === "ready" ? "border-emerald-300/25 text-emerald-100" : version.status === "errored" ? "border-red-300/25 text-red-100" : "border-white/15 text-slate-300"}`}>{version.status === "ready" ? "可播放" : version.status === "retired" ? "已退役" : version.status === "errored" ? "處理失敗" : "處理中"}</span><span className="text-xs text-slate-500">{new Date(version.created_at).toLocaleDateString("zh-TW")}</span></div></article>; }) : <p className="rounded-xl border border-white/10 p-5 text-sm text-slate-400">目前沒有影片版本紀錄。</p>}</div></section>;
  if (view === "questions") return <section className="mt-5 rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-200">Questions</p><h2 className="mt-2 text-xl font-semibold">學生提問</h2><p className="mt-2 text-sm text-slate-400">依課程與時間點整理問題和「這段看不懂」訊號；回答與解決會保留處理狀態。</p></div><div className="mt-5 space-y-3">{questions.length ? questions.map((question, index) => { const lesson = lessons.find((item) => item.id === question.lesson_id); return <article key={question.id ?? `${question.lesson_id}-${question.timestamp_seconds}-${index}`} className="rounded-xl border border-white/10 bg-slate-950/50 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold text-white">{lesson?.title ?? "課程單元"}</p><p className="mt-1 text-sm text-cyan-100">{Math.floor(question.timestamp_seconds / 60)}:{String(question.timestamp_seconds % 60).padStart(2, "0")} · {question.kind === "unclear" ? "這段看不懂" : "學生提問"}</p></div><span className="text-xs text-slate-500">{question.status === "open" ? "待處理" : question.status === "answered" ? "已回答" : "已解決"}</span></div>{question.body ? <p className="mt-3 rounded-lg border border-white/10 bg-white/[0.03] px-3 py-2 text-sm leading-6 text-slate-200">{question.body}</p> : null}<Link href={`/admin/course?edit=${question.lesson_id}&t=${question.timestamp_seconds}`} className="mt-3 inline-flex text-sm text-cyan-200 hover:text-white">從這一段預覽 →</Link><QuestionActions question={question} /></article>; }) : <p className="rounded-xl border border-white/10 p-5 text-sm text-slate-400">目前沒有學生提問。</p>}</div></section>;
  if (view === "analytics") return <section className="mt-5 rounded-2xl border border-white/10 bg-white/[0.035] p-5"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-200">Learning Analytics</p><h2 className="mt-2 text-xl font-semibold">學習數據</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="text-xs text-slate-500"><tr><th className="px-3 py-3">課程</th><th>觀看人數</th><th>完成率</th><th>平均觀看</th><th>到達 50%</th><th>到達 80%</th><th>提問</th></tr></thead><tbody>{metrics.map(({ lesson, metric }) => <tr key={lesson.id} className="border-t border-white/10"><td className="px-3 py-4"><p className="font-semibold text-white">{lesson.title}</p><div className="mt-2 flex flex-wrap gap-2"><StateBadge state={lesson.publication_state} />{metric.sampleMessage ? <span className="text-xs text-slate-500">{metric.sampleMessage}</span> : null}</div></td><td className="text-slate-300">{metric.learners}</td><td className="text-slate-300">{metric.completionRate === null ? "-" : `${metric.completionRate}%`}</td><td className="text-slate-300">{formatWatchTime(metric.averageWatchSeconds)}</td><td className="text-slate-300">{metric.reached50}</td><td className="text-slate-300">{metric.reached80}</td><td className="text-slate-300">{metric.questions + metric.unclearSignals}</td></tr>)}</tbody></table></div></section>;
  const attention = metrics.filter(({ metric }) => metric.replayHotspots > 0 || metric.questions + metric.unclearSignals > 0 || metric.dropOffHotspots > 0);
  return <section className="mt-5 rounded-2xl border border-amber-300/20 bg-amber-300/[0.04] p-5"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-amber-100">Attention Center</p><h2 className="mt-2 text-xl font-semibold">待處理</h2><p className="mt-2 text-sm text-slate-400">先處理有明確觀看、重看或提問證據的課程，不以不透明分數排序。</p><div className="mt-5 space-y-3">{attention.length ? attention.map(({ lesson, metric }) => <article key={lesson.id} className="rounded-xl border border-white/10 bg-slate-950/50 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold text-white">{lesson.title}</h3><p className="mt-2 text-sm text-slate-300">{metric.replayHotspots ? `${metric.replayHotspots} 個重看片段` : null}{metric.replayHotspots && metric.questions + metric.unclearSignals ? " · " : null}{metric.questions + metric.unclearSignals ? `${metric.questions + metric.unclearSignals} 個學生訊號` : null}</p></div><StateBadge state={lesson.publication_state} /></div><div className="mt-4 flex flex-wrap gap-2"><Link href={`/admin/course?edit=${lesson.id}`} className="rounded-lg border border-cyan-300/25 px-3 py-2 text-xs font-semibold text-cyan-100">查看課程</Link><Link href={`/admin/course?view=analytics&edit=${lesson.id}`} className="rounded-lg border border-white/10 px-3 py-2 text-xs font-semibold text-slate-200">查看數據</Link><Link href={`/admin/course?view=questions&edit=${lesson.id}`} className="rounded-lg border border-white/10 px-3 py-2 text-xs font-semibold text-slate-200">查看提問</Link></div></article>) : <p className="rounded-xl border border-emerald-300/20 bg-emerald-300/[0.05] p-5 text-sm text-emerald-100">目前沒有需要立即處理的學習訊號。</p>}</div></section>;
}
